/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_e379089b (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/hbfnznazboimbzlpcnkg/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const KV_TABLE = Deno.env.get("KV_STORE_TABLE") || "kv_store_e379089b";
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SUPABASE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || Deno.env.get("SUPABASE_ANON_KEY") || "";

const client = () => createClient(
  SUPABASE_URL,
  SUPABASE_KEY,
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from(KV_TABLE).upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from(KV_TABLE).select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from(KV_TABLE).delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from(KV_TABLE).upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from(KV_TABLE).select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  const byKey = new Map<string, any>((data ?? []).map((d: any) => [d.key, d.value]));
  return keys.map((key) => byKey.get(key));
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from(KV_TABLE).delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from(KV_TABLE).select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Import multiple items, updating existing ones by SKU
export const importItems = async (items: any[]): Promise<{ imported: number; errors: string[] }> => {
  const existingItems = await getByPrefix('item:');
  const errors: string[] = [];
  let imported = 0;

  for (let i = 0; i < items.length; i++) {
    try {
      const itemData = items[i];

      // Validate required fields
      if (!itemData.name || !itemData.sku) {
        errors.push(`Row ${i + 1}: Missing required fields (name, sku)`);
        continue;
      }

      // Check if item already exists by SKU
      const existingItem = existingItems.find((item: any) => item.sku === itemData.sku);

      if (existingItem) {
        // Update existing item
        const updatedItem = {
          ...existingItem,
          ...itemData,
          updatedAt: new Date().toISOString()
        };
        await set(`item:${existingItem.id}`, updatedItem);
      } else {
        // Create new item
        const id = crypto.randomUUID();
        const newItem = {
          ...itemData,
          id,
          createdAt: new Date().toISOString()
        };
        await set(`item:${id}`, newItem);
      }

      imported++;
    } catch (err: any) {
      errors.push(`Row ${i + 1}: ${err.message}`);
    }
  }

  return { imported, errors };
};
